// {{ .Name }} — generated by rda from the web-go template.
//
// Discovers a Postgres / MariaDB / Redis / Kafka binding via the
// Kubernetes Service Binding Specification (SBS) — discovery by TYPE,
// not by NAME. Iterates $SERVICE_BINDING_ROOT (default /bindings),
// reads each entry's `type` file, and returns the first binding
// whose type matches the query. The user's binding name (whatever
// they passed to `rda add-service <type> <binding>`) is irrelevant
// to this app — same convention as Paketo / Spring Cloud Bindings.
//
// Multi-DB pin: set DB_BINDING_NAME=<binding> when there are multiple
// bindings of the same type and you need a specific one. Without the
// override, the first matching binding wins.
//
// Falls back to "no database configured" when no matching binding is
// found so the liveness probe still passes during local development.

package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	port := envOrDefault("PORT", "8080")
	bindingRoot := envOrDefault("SERVICE_BINDING_ROOT", "/bindings")

	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, _ *http.Request) {
		db := findBindingByType(bindingRoot, "postgresql")
		if db == nil {
			db = findBindingByType(bindingRoot, "mariadb")
		}
		body := map[string]any{
			"service":  "{{ .Name }}",
			"language": "{{ .Language }}",
		}
		if db != nil {
			body["database"] = map[string]string{
				"type":     db["type"],
				"provider": db["provider"],
				"host":     db["host"],
				"port":     db["port"],
				"database": db["database"],
				// password is intentionally not exposed.
			}
		} else {
			body["database"] = "no postgresql or mariadb binding mounted"
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(body)
	})
	mux.HandleFunc("/health", func(w http.ResponseWriter, _ *http.Request) { _, _ = w.Write([]byte("ok")) })
	mux.HandleFunc("/ready", func(w http.ResponseWriter, _ *http.Request) { _, _ = w.Write([]byte("ok")) })

	addr := ":" + port
	log.Printf("{{ .Name }} listening on %s", addr)
	if db := findBindingByType(bindingRoot, "postgresql"); db != nil {
		log.Printf("  postgresql binding: host=%s:%s db=%s", db["host"], db["port"], db["database"])
	} else if db := findBindingByType(bindingRoot, "mariadb"); db != nil {
		log.Printf("  mariadb binding: host=%s:%s db=%s", db["host"], db["port"], db["database"])
	} else {
		log.Printf("  no postgresql or mariadb binding mounted")
	}
	if err := http.ListenAndServe(addr, mux); err != nil {
		log.Fatal(err)
	}
}

// readBinding reads every key under $SERVICE_BINDING_ROOT/<name>/ into
// a map[string]string. Returns nil when the directory is absent.
func readBinding(root, name string) map[string]string {
	dir := filepath.Join(root, name)
	if _, err := os.Stat(dir); err != nil {
		return nil
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil
	}
	out := map[string]string{}
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), ".") {
			continue
		}
		b, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			continue
		}
		out[e.Name()] = strings.TrimSpace(string(b))
	}
	return out
}

// findBindingByType walks the bindingRoot, picks the first binding
// whose `type` file matches targetType, and returns its content.
// Honours the DB_BINDING_NAME env override for the multi-binding
// case (e.g. services: [- binding: users-db, type: postgresql,
// - binding: events-db, type: postgresql]).
func findBindingByType(root, targetType string) map[string]string {
	if _, err := os.Stat(root); err != nil {
		return nil
	}
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil
	}
	override := os.Getenv("DB_BINDING_NAME")
	for _, e := range entries {
		name := e.Name()
		if strings.HasPrefix(name, ".") {
			continue
		}
		typePath := filepath.Join(root, name, "type")
		b, err := os.ReadFile(typePath)
		if err != nil {
			continue
		}
		if strings.TrimSpace(string(b)) != targetType {
			continue
		}
		if override != "" && name != override {
			continue
		}
		return readBinding(root, name)
	}
	return nil
}

func envOrDefault(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

// Force the unused-import for fmt to stay imported when the example
// expands; keeps the scaffold robust to small downstream tweaks.
var _ = fmt.Sprintf
