// {{ .Name }} — generated by rda from the web-go template.
//
// Go port of the web-nodejs Message Wall demo:
//   1. PostgreSQL binding (env vars projected from the SBS Secret).
//   2. Prometheus metrics on /metrics (HTTP duration histogram +
//      domain counters/gauges).
//   3. Optional OIDC login when <AUTH_BINDING>_PUBLIC_URL is set —
//      browser-side login via oidc-client-ts (CDN). AUTH_BINDING
//      defaults to 'AUTH'; override (e.g. AUTH_BINDING=idp) to read
//      from a different binding's PUBLIC_URL projection.
//   4. /admin endpoint — Bearer-token-validated server-side route.
//      When AUTH_ISSUER + OIDC_CLIENT_ID are set, /admin verifies an
//      id_token (Authorization: Bearer <jwt>) against the issuer's
//      JWKS endpoint via in-cluster URL (so localtest.me ingress URLs
//      stay browser-only — see InsecureIssuerURLContext rationale in
//      the verifier init below). Returns claims JSON on success, 401
//      on failure.  Browser-cookie session flow is a follow-on PR.
//
// The Postgres binding is read from env vars projected by the rda
// library helper (services[].binding=db => DB_HOST, DB_PORT,
// DB_USERNAME, DB_PASSWORD, DB_DATABASE). Set DB_BINDING=<binding>
// (uppercased) to override the prefix.

package main

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"html/template"
	"io"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/coreos/go-oidc/v3/oidc"
	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/collectors"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

// 🎨 Change this color, save, see it update!
const accentColor = "#736def"

var (
	dbPrefix     = strings.ToUpper(envOrDefault("DB_BINDING", "DB"))
	authPrefix   = strings.ToUpper(envOrDefault("AUTH_BINDING", "AUTH"))
	// authPublicURL is the browser-facing OIDC issuer URL — auto-derived
	// from services[].ingress.host by rda render + the binding-secret's
	// public_url key (bundle 0.11.27+). Empty when no auth binding is
	// configured; the home page renders without the login UI.
	authPublicURL = os.Getenv(authPrefix + "_PUBLIC_URL")
	// authIssuer is what tokens claim in their `iss` field — same value
	// as authPublicURL today (auto-derived together) but kept distinct
	// so apps can branch if a future config splits them.
	authIssuer = os.Getenv(authPrefix + "_ISSUER")
	// authURL is the in-cluster Service URL — what the pod uses to reach
	// dex's discovery + token + JWKS endpoints. Browser uses authPublicURL
	// (the ingress URL), pod uses authURL (svc.cluster.local). Without
	// this split, a localtest.me-only browser-facing URL wouldn't be
	// reachable from inside the cluster for token verification.
	authURL      = os.Getenv(authPrefix + "_URL")
	// Back-compat alias for projects that haven't migrated to AUTH_BINDING.
	dexPublicURL = authPublicURL
	oidcClientID = envOrDefault("OIDC_CLIENT_ID", "message-wall")
	startTime    = time.Now()

	// OIDC verifier — populated in main() if OIDC is configured.
	// nil otherwise; /admin returns 503 in that case.
	oidcVerifier *oidc.IDTokenVerifier

	// Prometheus registry — explicit (vs default) so tests can drive it.
	registry = prometheus.NewRegistry()

	httpDuration = promauto.With(registry).NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "app_http_request_duration_seconds",
			Help:    "Duration of HTTP requests in seconds",
			Buckets: []float64{0.005, 0.01, 0.05, 0.1, 0.5, 1},
		},
		[]string{"method", "path", "status"},
	)
	messagesPosted = promauto.With(registry).NewCounter(prometheus.CounterOpts{
		Name: "app_messages_posted_total",
		Help: "Total number of messages posted",
	})
	messagesDeleted = promauto.With(registry).NewCounter(prometheus.CounterOpts{
		Name: "app_messages_deleted_total",
		Help: "Total number of bulk deletes",
	})
	messagesCurrent = promauto.With(registry).NewGauge(prometheus.GaugeOpts{
		Name: "app_messages_count",
		Help: "Current number of messages in the database",
	})
)

func main() {
	registry.MustRegister(collectors.NewGoCollector(), collectors.NewProcessCollector(collectors.ProcessCollectorOpts{}))

	// OIDC bootstrap. Only fires when the binding contract is satisfied:
	// AUTH_URL (in-cluster, reachable for JWKS fetch) AND AUTH_ISSUER
	// (what tokens claim) AND OIDC_CLIENT_ID. Missing any → /admin
	// returns 503 with a remediation hint.
	//
	// Why split URLs: dex sets discovery's `issuer` + jwks_uri using
	// the chart's config.issuer (= AUTH_ISSUER, browser-facing). Pods
	// inside the cluster can't resolve auth.test.localtest.me. We
	// build the keyset directly from <AUTH_URL>/keys (in-cluster) and
	// configure the verifier to expect AUTH_ISSUER in the `iss` claim.
	if authURL != "" && authIssuer != "" && oidcClientID != "" {
		ctx := context.Background()
		keySet := oidc.NewRemoteKeySet(ctx, authURL+"/keys")
		oidcVerifier = oidc.NewVerifier(authIssuer, keySet, &oidc.Config{ClientID: oidcClientID})
		log.Printf("🔐 OIDC verifier ready (issuer=%s, jwks=%s/keys, client=%s)", authIssuer, authURL, oidcClientID)
	} else {
		log.Printf("ℹ️  OIDC verifier disabled — set <%s>_URL, <%s>_ISSUER, OIDC_CLIENT_ID to enable /admin", authPrefix, authPrefix)
	}

	port := envOrDefault("PORT", "8080")

	// Postgres is OPTIONAL. If <DB_PREFIX>_HOST is unset (no postgres binding),
	// the Message Wall API is disabled and the home page shows a friendly
	// 'no DB bound' placeholder instead. /metrics, /health, /ready still
	// work without postgres so the pod stays Ready.
	host := envWithPrefix("HOST", "")
	dbEnabled := host != ""
	var db *sql.DB
	if !dbEnabled {
		log.Printf("ℹ️  No %s_HOST in env — postgres binding not configured; serving placeholder home page.", dbPrefix)
		log.Printf("   To enable Message Wall: rda add-service postgresql %s, flip enabled:true, fill auth slots.", strings.ToLower(dbPrefix))
	} else {
		dsn := fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=disable",
			host,
			envWithPrefix("PORT", "5432"),
			envWithPrefix("USERNAME", ""),
			envWithPrefix("PASSWORD", ""),
			envWithPrefix("DATABASE", ""),
		)

		var err error
		db, err = sql.Open("pgx", dsn)
		if err != nil {
			log.Fatalf("💀 sql.Open: %v", err)
		}
		defer db.Close()

		// Retry the initial Ping — postgres often isn't Ready when the app
		// pod starts (helm install kicks both in parallel; postgres init
		// takes 5-15s). A Fatal exit here loops us in CrashLoop with k8s
		// recreating us before postgres comes up. Retrying gives postgres
		// time to finish init while we keep the process alive.
		{
			const maxAttempts = 60
			const delay = 2 * time.Second
			var lastErr error
			for attempt := 1; attempt <= maxAttempts; attempt++ {
				ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
				err := db.PingContext(ctx)
				cancel()
				if err == nil {
					lastErr = nil
					break
				}
				lastErr = err
				if attempt == maxAttempts {
					break
				}
				log.Printf("⏳ postgres not ready yet (attempt %d/%d: %v); retrying in %s…",
					attempt, maxAttempts, err, delay)
				time.Sleep(delay)
			}
			if lastErr != nil {
				log.Fatalf("💀 db.Ping after %d attempts: %v", maxAttempts, lastErr)
			}
		}
		log.Printf("✅ Connected to PostgreSQL at %s:%s", host, envWithPrefix("PORT", "5432"))

		if _, err := db.Exec(`
			CREATE TABLE IF NOT EXISTS messages (
				id         SERIAL PRIMARY KEY,
				body       TEXT NOT NULL CHECK (char_length(body) <= 280),
				created_at TIMESTAMPTZ DEFAULT NOW()
			)`); err != nil {
			log.Fatalf("💀 create table: %v", err)
		}
		log.Printf("✅ Table ready")

		// Seed gauge with current count.
		var initial int
		if err := db.QueryRow(`SELECT COUNT(*) FROM messages`).Scan(&initial); err == nil {
			messagesCurrent.Set(float64(initial))
		}
	}

	tpl := template.Must(template.New("page").Parse(htmlPage))

	mux := http.NewServeMux()

	mux.Handle("/metrics", promhttp.HandlerFor(registry, promhttp.HandlerOpts{}))

	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/" {
			http.NotFound(w, r)
			return
		}
		t := time.Now()
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_ = tpl.Execute(w, pageData{
			Name:         "{{ .Name }}",
			Accent:       accentColor,
			DexPublicURL: dexPublicURL,
			OIDCClientID: oidcClientID,
		})
		observe("GET", "/", 200, t)
	})

	mux.HandleFunc("/api/messages", func(w http.ResponseWriter, r *http.Request) {
		t := time.Now()
		if !dbEnabled {
			http.Error(w, "messages api unavailable: no postgres binding configured (set services[].type=postgresql in deploy/values.yaml)", http.StatusServiceUnavailable)
			observe(r.Method, "/api/messages", 503, t)
			return
		}
		switch r.Method {
		case http.MethodGet:
			rows, err := db.Query(`SELECT id, body, created_at FROM messages ORDER BY created_at DESC LIMIT 50`)
			if err != nil {
				httpJSONError(w, 500, err)
				observe("GET", "/api/messages", 500, t)
				return
			}
			defer rows.Close()
			out := []messageDTO{}
			for rows.Next() {
				var m messageDTO
				if err := rows.Scan(&m.ID, &m.Body, &m.CreatedAt); err != nil {
					httpJSONError(w, 500, err)
					observe("GET", "/api/messages", 500, t)
					return
				}
				out = append(out, m)
			}
			var total int
			_ = db.QueryRow(`SELECT COUNT(*) FROM messages`).Scan(&total)
			messagesCurrent.Set(float64(total))
			w.Header().Set("Content-Type", "application/json")
			_ = json.NewEncoder(w).Encode(map[string]any{
				"messages": out,
				"total":    total,
				"pod":      envOrDefault("HOSTNAME", "local"),
				"uptime":   time.Since(startTime).Seconds(),
			})
			observe("GET", "/api/messages", 200, t)

		case http.MethodPost:
			body, err := io.ReadAll(r.Body)
			if err != nil {
				httpJSONError(w, 400, err)
				observe("POST", "/api/messages", 400, t)
				return
			}
			var in struct {
				Body string `json:"body"`
			}
			if err := json.Unmarshal(body, &in); err != nil || strings.TrimSpace(in.Body) == "" {
				httpJSONError(w, 400, fmt.Errorf("body is required"))
				observe("POST", "/api/messages", 400, t)
				return
			}
			trimmed := strings.TrimSpace(in.Body)
			if len(trimmed) > 280 {
				trimmed = trimmed[:280]
			}
			var m messageDTO
			err = db.QueryRow(
				`INSERT INTO messages (body) VALUES ($1) RETURNING id, body, created_at`,
				trimmed,
			).Scan(&m.ID, &m.Body, &m.CreatedAt)
			if err != nil {
				httpJSONError(w, 500, err)
				observe("POST", "/api/messages", 500, t)
				return
			}
			messagesPosted.Inc()
			messagesCurrent.Inc()
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(201)
			_ = json.NewEncoder(w).Encode(m)
			observe("POST", "/api/messages", 201, t)

		case http.MethodDelete:
			if _, err := db.Exec(`DELETE FROM messages`); err != nil {
				httpJSONError(w, 500, err)
				observe("DELETE", "/api/messages", 500, t)
				return
			}
			messagesDeleted.Inc()
			messagesCurrent.Set(0)
			w.Header().Set("Content-Type", "application/json")
			_ = json.NewEncoder(w).Encode(map[string]bool{"deleted": true})
			observe("DELETE", "/api/messages", 200, t)

		default:
			http.Error(w, "method not allowed", 405)
		}
	})

	// /admin — protected route. Validates an Authorization: Bearer
	// <jwt> against the OIDC verifier (configured at startup from
	// AUTH_URL + AUTH_ISSUER + OIDC_CLIENT_ID). Returns the token's
	// claims as JSON on success.
	//
	// To get a token from the dex IdP:
	//   curl -X POST <AUTH_URL>/token \\
	//     -d grant_type=password -d username=<staticPasswords email> \\
	//     -d password=... -d client_id=<staticClient id> \\
	//     -d client_secret=... -d "scope=openid profile email"
	// Then:
	//   curl -H "Authorization: Bearer <id_token>" http://<app>/admin
	//
	// Browser-cookie session flow (/login → /auth/callback → cookie)
	// is the next step — currently this route is API-only.
	mux.HandleFunc("/admin", func(w http.ResponseWriter, r *http.Request) {
		t := time.Now()
		if oidcVerifier == nil {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(503)
			_ = json.NewEncoder(w).Encode(map[string]string{
				"error": "oidc not configured",
				"hint":  "set AUTH_BINDING (or bind dex via rda add-service dex auth) and OIDC_CLIENT_ID env",
			})
			observe(r.Method, "/admin", 503, t)
			return
		}
		authHdr := r.Header.Get("Authorization")
		if !strings.HasPrefix(authHdr, "Bearer ") {
			w.Header().Set("Content-Type", "application/json")
			w.Header().Set("WWW-Authenticate", "Bearer realm=\""+authIssuer+"\"")
			w.WriteHeader(401)
			_ = json.NewEncoder(w).Encode(map[string]string{
				"error": "missing or malformed Authorization: Bearer <jwt> header",
				"issuer": authIssuer,
			})
			observe(r.Method, "/admin", 401, t)
			return
		}
		rawIDToken := strings.TrimPrefix(authHdr, "Bearer ")
		idToken, err := oidcVerifier.Verify(r.Context(), rawIDToken)
		if err != nil {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(401)
			_ = json.NewEncoder(w).Encode(map[string]string{
				"error": "id_token verification failed: " + err.Error(),
			})
			observe(r.Method, "/admin", 401, t)
			return
		}
		var claims map[string]any
		if err := idToken.Claims(&claims); err != nil {
			httpJSONError(w, 500, fmt.Errorf("unmarshal claims: %w", err))
			observe(r.Method, "/admin", 500, t)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{
			"authenticated": true,
			"subject":       idToken.Subject,
			"issuer":        idToken.Issuer,
			"audience":      idToken.Audience,
			"expires_at":    idToken.Expiry,
			"claims":        claims,
		})
		observe(r.Method, "/admin", 200, t)
	})

	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		t := time.Now()
		_, _ = w.Write([]byte("ok"))
		observe(r.Method, "/health", 200, t)
	})

	mux.HandleFunc("/ready", func(w http.ResponseWriter, r *http.Request) {
		t := time.Now()
		if dbEnabled {
			ctx, cancel := context.WithTimeout(r.Context(), 2*time.Second)
			defer cancel()
			if err := db.PingContext(ctx); err != nil {
				http.Error(w, "not-ready: "+err.Error(), 503)
				observe(r.Method, "/ready", 503, t)
				return
			}
		}
		_, _ = w.Write([]byte("ready"))
		observe(r.Method, "/ready", 200, t)
	})

	addr := ":" + port
	log.Printf("🚀 Server running on http://localhost%s", addr)
	log.Printf("📊 Metrics at http://localhost%s/metrics", addr)
	if authPublicURL != "" {
		log.Printf("🔐 OIDC: %s", authPublicURL)
	}
	if err := http.ListenAndServe(addr, mux); err != nil {
		log.Fatal(err)
	}
}

type messageDTO struct {
	ID        int64     `json:"id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
}

type pageData struct {
	Name         string
	Accent       string
	DexPublicURL string
	OIDCClientID string
}

func observe(method, path string, status int, t time.Time) {
	httpDuration.WithLabelValues(method, path, strconv.Itoa(status)).Observe(time.Since(t).Seconds())
}

func httpJSONError(w http.ResponseWriter, code int, err error) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	_ = json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
}

// envOrDefault returns os.Getenv(key) if non-empty else def.
func envOrDefault(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

// envWithPrefix returns os.Getenv(<dbPrefix>_<suffix>) if non-empty else fb.
func envWithPrefix(suffix, fb string) string {
	return envOrDefault(dbPrefix+"_"+suffix, fb)
}

// htmlPage is the single-file HTML/JS UI. Identical layout to the
// web-nodejs sibling so the two demos render the same.
const htmlPage = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{.Name}} · Message Wall</title>
  <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>📬</text></svg>">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    :root { --accent: {{.Accent}}; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
      background: #0f172a; color: #e2e8f0; min-height: 100vh; display: flex;
      flex-direction: column; align-items: center; }
    header { width: 100%; padding: 2rem; text-align: center;
      background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%);
      border-bottom: 1px solid #1e293b; }
    header h1 { font-size: 1.8rem; font-weight: 700; color: var(--accent); }
    header p { color: #64748b; margin-top: 0.4rem; font-size: 0.9rem; }
    .info-bar { display: flex; gap: 1.5rem; justify-content: center; margin-top: 1rem; flex-wrap: wrap; }
    .info-pill { display: flex; align-items: center; gap: 0.4rem; background: #1e293b;
      padding: 0.35rem 0.8rem; border-radius: 999px; font-size: 0.75rem; color: #94a3b8;
      border: 1px solid #334155; }
    .info-pill .dot { width: 6px; height: 6px; border-radius: 50%; background: #22c55e;
      animation: pulse 2s infinite; }
    @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }
    main { width: 100%; max-width: 640px; padding: 1.5rem; flex: 1; }
    .compose { display: flex; gap: 0.5rem; margin-bottom: 1.5rem; }
    .compose input[type="text"] { flex: 1; padding: 0.75rem 1rem; border-radius: 0.75rem;
      border: 1px solid #334155; background: #1e293b; color: #e2e8f0; font-size: 0.95rem;
      outline: none; transition: border-color 0.2s; }
    .compose input[type="text"]:focus { border-color: var(--accent); }
    .compose input[type="text"]::placeholder { color: #475569; }
    .compose button { padding: 0.75rem 1.5rem; border-radius: 0.75rem; border: none;
      background: var(--accent); color: white; font-weight: 600; font-size: 0.95rem;
      cursor: pointer; transition: opacity 0.2s; white-space: nowrap; }
    .compose button:hover { opacity: 0.85; }
    .compose button:disabled { opacity: 0.4; cursor: not-allowed; }
    .clear-btn { padding: 0.75rem; border-radius: 0.75rem; border: 1px solid #334155;
      background: #1e293b; font-size: 1rem; cursor: pointer; transition: border-color 0.2s; }
    .clear-btn:hover { border-color: #ef4444; }
    .messages { display: flex; flex-direction: column; gap: 0.6rem; }
    .msg { background: #1e293b; border: 1px solid #334155; border-radius: 0.75rem;
      padding: 0.85rem 1rem; display: flex; justify-content: space-between;
      align-items: flex-start; gap: 1rem; }
    .msg.new { animation: slideIn 0.3s ease-out; }
    @keyframes slideIn { from { opacity: 0; transform: translateY(-8px); }
      to { opacity: 1; transform: translateY(0); } }
    .msg-text { font-size: 0.95rem; line-height: 1.5; word-break: break-word; }
    .msg-meta { font-size: 0.7rem; color: #475569; white-space: nowrap; padding-top: 0.15rem; }
    .empty { text-align: center; color: #475569; padding: 3rem 1rem; font-size: 0.95rem; }
    footer { width: 100%; text-align: center; padding: 1.5rem; color: #334155; font-size: 0.75rem; }
    footer code { color: var(--accent); }
  </style>
</head>
<body>
  <header>
    <h1>📮 {{.Name}} — Message Wall</h1>
    <p>A tiny app running in Kubernetes — powered by Tilt + Rancher Desktop</p>
    <div class="info-bar">
      <div class="info-pill"><span class="dot"></span> <span id="pod">—</span></div>
      <div class="info-pill">⏱ Uptime: <span id="uptime">—</span></div>
      <div class="info-pill">💬 <span id="count">0</span> messages</div>
      {{if .DexPublicURL}}<div class="info-pill">🔐 <span id="username">…</span> <a id="logout-btn" href="#" style="margin-left:0.4rem;color:#ef4444;text-decoration:none;font-weight:600;display:none" title="Logout">✕</a></div>{{end}}
    </div>
  </header>
  <main>
    <form class="compose" onsubmit="send(event)">
      <input type="text" id="input" placeholder="Say something…" autocomplete="off" maxlength="280" autofocus />
      <button type="submit" id="btn">Post</button>
      <button type="button" onclick="clear_()" class="clear-btn" title="Delete all messages">🧹</button>
    </form>
    <div class="messages" id="messages"></div>
  </main>
  <footer>
    Change <code>accentColor</code> in main.go → save → see it update here ✨
  </footer>
  <script>
    const msgBox = document.getElementById('messages');
    const input  = document.getElementById('input');
    const btn    = document.getElementById('btn');
    const podEl  = document.getElementById('pod');
    const upEl   = document.getElementById('uptime');
    const cntEl  = document.getElementById('count');
    let knownIds = new Set();

    function timeAgo(ts) {
      const s = Math.floor((Date.now() - new Date(ts).getTime()) / 1000);
      if (s < 60)   return s + 's ago';
      if (s < 3600) return Math.floor(s / 60) + 'm ago';
      if (s < 86400) return Math.floor(s / 3600) + 'h ago';
      return Math.floor(s / 86400) + 'd ago';
    }
    function fmtUptime(s) {
      if (s < 60)   return Math.floor(s) + 's';
      if (s < 3600) return Math.floor(s / 60) + 'm ' + Math.floor(s % 60) + 's';
      return Math.floor(s / 3600) + 'h ' + Math.floor((s % 3600) / 60) + 'm';
    }
    function esc(t) { const d = document.createElement('div'); d.textContent = t; return d.innerHTML; }

    async function load() {
      try {
        const r = await fetch('/api/messages');
        const d = await r.json();
        podEl.textContent = d.pod;
        upEl.textContent  = fmtUptime(d.uptime);
        cntEl.textContent = d.total;
        if (!d.messages.length) {
          msgBox.innerHTML = '<div class="empty">No messages yet — be the first! 🎉</div>';
          knownIds.clear(); return;
        }
        const currentIds  = d.messages.map(m => m.id).join(',');
        const previousIds = [...msgBox.querySelectorAll('.msg')].map(e => e.dataset.id).join(',');
        if (currentIds !== previousIds) {
          msgBox.innerHTML = d.messages.map(m => {
            const isNew = !knownIds.has(m.id);
            return '<div class="msg' + (isNew ? ' new' : '') + '" data-id="' + m.id + '">' +
              '<span class="msg-text">' + esc(m.body) + '</span>' +
              '<span class="msg-meta">' + timeAgo(m.created_at) + '</span>' +
            '</div>';
          }).join('');
        } else {
          msgBox.querySelectorAll('.msg').forEach((el, i) => {
            el.querySelector('.msg-meta').textContent = timeAgo(d.messages[i].created_at);
          });
        }
        knownIds = new Set(d.messages.map(m => m.id));
      } catch (e) {
        msgBox.innerHTML = '<div class="empty">⚠️ Cannot reach API</div>';
      }
    }

    async function send(e) {
      e.preventDefault();
      const body = input.value.trim();
      if (!body) return;
      btn.disabled = true;
      try {
        await fetch('/api/messages', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ body }),
        });
        input.value = '';
        await load();
      } finally { btn.disabled = false; }
      input.focus();
    }

    async function clear_() {
      if (!confirm('Delete all messages?')) return;
      await fetch('/api/messages', { method: 'DELETE' });
      knownIds.clear();
      await load();
    }
    window._appLoad = load;
    {{if not .DexPublicURL}}
    load();
    setInterval(load, 3000);
    {{end}}
  </script>
  {{if .DexPublicURL}}
  <script type="module">
    function startApp() { window._appLoad(); setInterval(window._appLoad, 3000); }
    try {
      const { UserManager, WebStorageStateStore } = await import('https://cdn.jsdelivr.net/npm/oidc-client-ts@3/+esm');
      const um = new UserManager({
        authority: '{{.DexPublicURL}}',
        client_id: '{{.OIDCClientID}}',
        redirect_uri: window.location.origin + '/',
        post_logout_redirect_uri: window.location.origin + '/',
        response_type: 'code',
        scope: 'openid profile email',
        userStore: new WebStorageStateStore({ store: window.localStorage }),
      });
      if (window.location.search.includes('code=')) {
        await um.signinRedirectCallback();
        history.replaceState({}, document.title, window.location.pathname);
      }
      let user = await um.getUser();
      if (!user || user.expired) {
        await um.signinRedirect();
        return;
      }
      const name = (user.profile && (user.profile.preferred_username || user.profile.name || user.profile.email)) || 'user';
      document.getElementById('username').textContent = name;
      const logoutBtn = document.getElementById('logout-btn');
      if (logoutBtn) {
        logoutBtn.style.display = 'inline';
        logoutBtn.addEventListener('click', (e) => { e.preventDefault(); um.signoutRedirect(); });
      }
      startApp();
    } catch (err) {
      console.warn('Dex/OIDC not available:', err);
      const el = document.getElementById('username'); if (el) el.textContent = '(no auth)';
      startApp();
    }
  </script>
  {{end}}
</body>
</html>`
