apiVersion: v2
name: {{ .Name }}
description: {{ .Name }} — infrastructure services environment
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords: [rda, infrastructure, services-only]

dependencies:
  - name: suse-library
    version: 0.15.0
