// {{ .Name }} — generated by rda from the web-nodejs template.
//
// Discovers a Postgres binding via the Kubernetes Service Binding
// Specification (SBS) — discovery by TYPE, not by NAME. Iterates
// $SERVICE_BINDING_ROOT (default /bindings), reads each entry's
// `type` file, and returns the first binding whose type is
// `postgresql`. The user's binding name (whatever they passed to
// `rda add-service postgresql <binding>`) is irrelevant to this
// app — same convention as Paketo / Spring Cloud Bindings, so the
// example app stays a faithful SBS reference.
//
// Multi-DB pin: set DB_BINDING_NAME=<binding> when there are
// multiple postgresql bindings and you need a specific one.
// Without the override, the first matching binding wins.
//
// Falls back to "no database configured" when no postgresql
// binding is found so the liveness probe still passes during
// local development without services.

const express = require('express');
const fs = require('fs');
const path = require('path');

const app = express();
const port = parseInt(process.env.PORT || '8080', 10);
const bindingRoot = process.env.SERVICE_BINDING_ROOT || '/bindings';

// readBinding reads every key under $SERVICE_BINDING_ROOT/<name>/
// into a plain object. Returns null when the directory is absent.
function readBinding(name) {
  const dir = path.join(bindingRoot, name);
  if (!fs.existsSync(dir)) {
    return null;
  }
  const result = {};
  for (const key of fs.readdirSync(dir)) {
    if (key.startsWith('.')) continue;
    try {
      result[key] = fs.readFileSync(path.join(dir, key), 'utf8').trim();
    } catch (e) {
      // ignore unreadable entries (rare; e.g. mid-rotation Secrets)
    }
  }
  return result;
}

// findBindingByType walks the bindingRoot, picks the first binding
// whose `type` file matches targetType, and returns its content.
// Honours the DB_BINDING_NAME env override for the multi-binding
// case (e.g. services: [- binding: users-db, type: postgresql,
// - binding: events-db, type: postgresql]).
function findBindingByType(targetType) {
  if (!fs.existsSync(bindingRoot)) {
    return null;
  }
  const override = process.env.DB_BINDING_NAME;
  for (const name of fs.readdirSync(bindingRoot)) {
    if (name.startsWith('.')) continue;
    const dir = path.join(bindingRoot, name);
    const typePath = path.join(dir, 'type');
    if (!fs.existsSync(typePath)) continue;
    let type;
    try {
      type = fs.readFileSync(typePath, 'utf8').trim();
    } catch (e) {
      continue;
    }
    if (type !== targetType) continue;
    if (override && name !== override) continue;
    return readBinding(name);
  }
  return null;
}

app.get('/', (_req, res) => {
  const database = findBindingByType('postgresql');
  res.json({
    service: '{{ .Name }}',
    language: '{{ .Language }}',
    database: database
      ? {
          type: database.type,
          provider: database.provider,
          host: database.host,
          port: database.port,
          database: database.database,
          // password is intentionally not exposed in the response
        }
      : 'no postgresql binding mounted',
  });
});

app.get('/health', (_req, res) => res.send('ok'));
app.get('/ready', (_req, res) => res.send('ok'));

app.listen(port, '0.0.0.0', () => {
  console.log(`{{ .Name }} listening on :${port}`);
  const database = findBindingByType('postgresql');
  if (database) {
    console.log(
      `  postgresql binding: host=${database.host}:${database.port} db=${database.database}`,
    );
  } else {
    console.log('  no postgresql binding mounted');
  }
});
