// {{ .Name }} — generated by rda from the web-nodejs template.
//
// Reads database credentials from the Kubernetes Service Binding
// Specification mount at $SERVICE_BINDING_ROOT/database/. Falls back
// to "no database configured" when the binding is absent so the
// liveness probe still passes during local development without
// services.

const express = require('express');
const fs = require('fs');
const path = require('path');

const app = express();
const port = parseInt(process.env.PORT || '8080', 10);
const bindingRoot = process.env.SERVICE_BINDING_ROOT || '/bindings';

function readBinding(name) {
  const dir = path.join(bindingRoot, name);
  if (!fs.existsSync(dir)) {
    return null;
  }
  const result = {};
  for (const key of fs.readdirSync(dir)) {
    if (key.startsWith('.')) continue;
    try {
      result[key] = fs.readFileSync(path.join(dir, key), 'utf8').trim();
    } catch (e) {
      // ignore unreadable entries
    }
  }
  return result;
}

app.get('/', (_req, res) => {
  const database = readBinding('database');
  res.json({
    service: '{{ .Name }}',
    language: '{{ .Language }}',
    database: database
      ? {
          type: database.type,
          provider: database.provider,
          host: database.host,
          port: database.port,
          database: database.database,
          // password is intentionally not exposed in the response
        }
      : 'no database binding mounted',
  });
});

app.get('/health', (_req, res) => res.send('ok'));
app.get('/ready', (_req, res) => res.send('ok'));

app.listen(port, '0.0.0.0', () => {
  console.log(`{{ .Name }} listening on :${port}`);
  const database = readBinding('database');
  if (database) {
    console.log(
      `  database binding: type=${database.type} host=${database.host}:${database.port} db=${database.database}`,
    );
  } else {
    console.log('  no database binding mounted');
  }
});
