// {{ .Name }} — generated by rda from the worker-nodejs template.
//
// Long-running background worker. No HTTP server. Reads any binding
// available under $SERVICE_BINDING_ROOT (default /bindings) and logs
// a heartbeat every 10s.
//
// The library chart deploys this as a regular Deployment; the only
// difference from web-* templates is no Service, no Ingress, no
// readiness probe. Upgrade it to your queue consumer of choice
// (kafkajs, ioredis, amqplib) — discovery still happens by binding
// TYPE, not by name.

const fs = require('fs');
const path = require('path');

const bindingRoot = process.env.SERVICE_BINDING_ROOT || '/bindings';

function readBinding(name) {
  const dir = path.join(bindingRoot, name);
  if (!fs.existsSync(dir)) {
    return null;
  }
  const result = {};
  for (const key of fs.readdirSync(dir)) {
    if (key.startsWith('.')) continue;
    try {
      result[key] = fs.readFileSync(path.join(dir, key), 'utf8').trim();
    } catch (e) {
      // ignore unreadable entries
    }
  }
  return result;
}

function listBindings() {
  if (!fs.existsSync(bindingRoot)) return [];
  return fs.readdirSync(bindingRoot).filter((name) => !name.startsWith('.'));
}

console.log(`{{ .Name }} worker starting (binding root: ${bindingRoot})`);

const bindings = listBindings();
if (bindings.length === 0) {
  console.log('  no bindings mounted — running with empty config');
} else {
  for (const name of bindings) {
    const b = readBinding(name);
    if (!b) continue;
    console.log(`  binding ${name}: type=${b.type} provider=${b.provider} host=${b.host}:${b.port}`);
  }
}

// Heartbeat loop. Replace with your real consumer (kafkajs.consumer.run,
// ioredis subscribe, amqplib channel.consume, ...). The point of this
// template is the SCAFFOLDING — the consumer logic is application-specific.
let tick = 0;
setInterval(() => {
  tick += 1;
  console.log(`{{ .Name }} heartbeat #${tick}`);
}, 10000);

// Stay alive: exit cleanly on SIGTERM (tilt down / rollout restart).
process.on('SIGTERM', () => {
  console.log('{{ .Name }} received SIGTERM, exiting');
  process.exit(0);
});
